<?php

use Illuminate\Database\Seeder;
use App\Exam;

class ExamSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['name' => 'Abdominoscopia'],
            ['name' => 'Abreugrafia'],
            ['name' => 'Adenograma'],
            ['name' => 'Amostragem'],
            ['name' => 'Análise molecular para a síndrome do X frágil'],
            ['name' => 'Antibiograma'],
            ['name' => 'Anuscopia'],
            ['name' => 'Biópsia'],
            ['name' => 'Calcemia'],
            ['name' => 'Capnometria'],
            ['name' => 'Carga viral'],
            ['name' => 'Cartão de Guthrie'],
            ['name' => 'Cateterismo'],
            ['name' => 'Cistocentese'],
            ['name' => 'Citometria de fluxo'],
            ['name' => 'Coagulograma'],
            ['name' => 'Colonoscopia'],
            ['name' => 'Coloração diferencial'],
            ['name' => 'Corante Sudan'],
            ['name' => 'Culdoscopia'],
            ['name' => 'CURB-65'],
            ['name' => 'Densitometria óssea'],
            ['name' => 'Dermatoscopia'],
            ['name' => 'Dieta de exclusão'],
            ['name' => 'Doença residual mínima'],
            ['name' => 'Doppler transcraniano'],
            ['name' => 'Ecodoppler carotídeo e vertebral'],
            ['name' => 'Ecodoppler venoso dos membros inferiores'],
            ['name' => 'Elastografia'],
            ['name' => 'Eletronistagmografia'],
            ['name' => 'ELISA'],
            ['name' => 'Escala de Equilíbrio de Berg'],
            ['name' => 'Escore de Bishop'],
            ['name' => 'Esofagografia'],
            ['name' => 'Esofagograma'],
            ['name' => 'Espéculo'],
            ['name' => 'Espermograma'],
            ['name' => 'Espirometria'],
            ['name' => 'Estetoscópio'],
            ['name' => 'Estudo da condução nervosa'],
            ['name' => 'Exame pré-nupcial'],
            ['name' => 'Falso positivo'],
            ['name' => 'Gasometria arterial'],
            ['name' => 'Glicorraquia'],
            ['name' => 'Glicosímetro'],
            ['name' => 'Glicosúria'],
            ['name' => 'Hemadsorção'],
            ['name' => 'Hemograma'],
            ['name' => 'Histerosalpingografia'],
            ['name' => 'Imagiologia médica'],
            ['name' => 'Imuno-histoquímica'],
            ['name' => 'Imunofenotipagem'],
            ['name' => 'Laringoscopia'],
            ['name' => 'Lesão intraepitelial de alto grau'],
            ['name' => 'Magnetoencefalografia'],
            ['name' => 'Manobra de Phalen'],
            ['name' => 'Manometria esofágica'],
            ['name' => 'Mielografia'],
            ['name' => 'Mielograma'],
            ['name' => 'MRI de difusão'],
            ['name' => 'Nasofaringoscopia'],
            ['name' => 'Nasofibrolaringoscopia'],
            ['name' => 'Nasofibroscopia'],
            ['name' => 'Neurofeedback'],
            ['name' => 'Neuroimagiologia'],
            ['name' => 'Perfil lipídico'],
            ['name' => 'Ph-metria esofágica'],
            ['name' => 'Potencial evocado'],
            ['name' => 'Pressão venosa central'],
            ['name' => 'Protocolo de Observação para o Diagnóstico de Autismo'],
            ['name' => 'Prova cruzada'],
            ['name' => 'Prova da tuberculina'],
            ['name' => 'Prova de aglutinação em látex'],
            ['name' => 'Punção aspirativa por agulha fina'],
            ['name' => 'Punção lombar'],
            ['name' => 'Reação de Agostini'],
            ['name' => 'Reação de Paul-Bunnell-Davidsohn'],
            ['name' => 'Sigmoidoscopia'],
            ['name' => 'Reação intradérmica'],
            ['name' => 'Retossigmoidoscopia'],
            ['name' => 'Sigmoidoscopia'],
            ['name' => 'Teste de Allen'],
            ['name' => 'Teste de Coombs'],
            ['name' => 'Teste de ácido nucleico'],
            ['name' => 'Teste de ADN'],
            ['name' => 'Teste de Ames'],
            ['name' => 'Teste de Ham'],
            ['name' => 'Teste de Dix-Hallpike'],
            ['name' => 'Teste do suor'],
            ['name' => 'Teste de gravidez'],
            ['name' => 'Teste de inclinação ortostática'],
            ['name' => 'Teste do nitroazul de tetrazólio'],
            ['name' => 'Teste no ponto de atendimento'],
            ['name' => 'Teste de Papanicolau'],
            ['name' => 'Teste do pezinho'],
            ['name' => 'Teste rápido de diagnóstico'],
            ['name' => 'Teste VDRL'],
            ['name' => 'Tipagem sanguínea'],
            ['name' => 'Tonometria'],
            ['name' => 'Toracocentese'],
            ['name' => 'Uranálise'],
            ['name' => 'Urocultura'],
            ['name' => 'Urografia'],
            ['name' => 'Vectoeletronistagmografia'],
            ['name' => 'Veia safena acessória anterior'],
            ['name' => 'Velocidade de hemossedimentação'],
            ['name' => 'Vitroscopia'],
            ['name' => 'Xenodiagnóstico'],
        ];

        Exam::insert($data);
    }
}
